### ISSUE TITLE
gpt4 medel is not working in discord bot

### ISSUE THREAD

**Issue by Arifsha40** [Ruu3f/freeGPT-discord-bot#1]
gpt4 medel is not working in discord bot

**Comment by Ruu3f** [comment]
Could you provide extra details, like what error are you getting?

**Comment by Ruu3f** [comment]
Sorry, misclicked on `Close with comment` instead of `Comment`.

**Comment by Arifsha40** [comment]
Hello
freeGPT
BOT
 — Today at 16:07
Hey there! What's up?

Aarif — Today at 16:08
write 1000 words article on how to make money online as a women write in html markdown formate

freeGPT
BOT
 — Today at 16:08
<class 'Exception'>

I get this error

**Comment by Ruu3f** [comment]
I see, I made a mistake. I fixed it, now it should work as expected.

**Comment by Arifsha40** [comment]
thank you good sir !!!

**Comment by Arifsha40** [comment]
write 1000 words article on how to make money online as a women
freeGPT
BOT
 — Today at 01:22
400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

**Comment by Ruu3f** [comment]
> write 1000 words article on how to make money online as a women freeGPT BOT — Today at 01:22 400 Bad Request (error code: 50035): Invalid Form Body In content: Must be 2000 or fewer in length.

Fixed, now the bot will send the resp in a file if resp > 2000.
