### ISSUE TITLE
Unable to fetch the response.

### ISSUE THREAD

**Issue by 6Xian9** [Ruu3f/freeGPT-discord-bot#5]
Prodia isnt functioning, I jsut get the error message "Unable to fetch the response." sent by the bot.
Furthermore gpt 4 isnt working as well

**Comment by Ruu3f** [comment]
What version are you using?

**Comment by 6Xian9** [comment]
sorry as clarification, what version of???

**Comment by 6Xian9** [comment]
I use version 1.2.6 of freegpt

**Comment by Ruu3f** [comment]
Use version 1.2.7.
